# Generated by Django 4.1.1 on 2022-10-29 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_cityproject_description_short_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('city_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.cityproject')),
            ],
        ),
    ]
