# Generated by Django 4.1.1 on 2022-11-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityproject',
            name='place_id',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='description_long',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='description_short',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
