# Generated by Django 4.1.1 on 2022-11-19 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_cityproject_place_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='city_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='places.cityproject'),
        ),
    ]
