# Generated by Django 4.1.1 on 2022-12-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
