# Generated by Django 4.1.1 on 2022-12-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproject',
            name='description_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='description_short',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='place_id',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
