# Generated by Django 4.1.1 on 2022-12-24 13:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_cityproject_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityproject',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cityproject',
            name='place_id',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
