# Generated by Django 4.1.1 on 2023-02-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_alter_cityproject_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(unique=True, upload_to=''),
        ),
    ]
