# Generated by Django 4.1.1 on 2023-02-28 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_alter_image_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CityProject',
            new_name='Place',
        ),
    ]
