# Generated by Django 4.1.1 on 2023-02-28 13:41

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_rename_cityproject_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='city_project',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='places.place', verbose_name='место, с которым связано изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='порядковый номер'),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='id места'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.TextField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
