# Generated by Django 4.1.1 on 2023-02-28 13:50

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_alter_image_place_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(null=True, on_delete=places.models.Place, related_name='images', to='places.place', verbose_name='место, с которым связано изображение'),
        ),
    ]
