# Generated by Django 4.1.1 on 2023-03-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_image_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
