# Generated by Django 4.1.1 on 2023-03-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_alter_image_order_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='краткое описание'),
        ),
    ]
