# Generated by Django 4.1.1 on 2023-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_remove_place_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.TextField(blank=True, default='', max_length=50, verbose_name='id места'),
        ),
    ]
